COPY Degrees(DegreeId, Dept, DegreeDescription, TotalECTS) FROM '/mnt/ramdisk/tables/Degrees.table' DELIMITER ',' CSV HEADER;
ALTER TABLE Degrees add primary key (DegreeId);
COPY Students(StudentId, StudentName, Address, BirthyearStudent, Gender) FROM '/mnt/ramdisk/tables/Students.table' DELIMITER ',' CSV HEADER;
ALTER TABLE Students add primary key (studentid);
COPY StudentRegistrationsToDegrees(StudentRegistrationId, StudentId, DegreeId, RegistrationYear) FROM '/mnt/ramdisk/tables/StudentRegistrationsToDegrees.table' DELIMITER ',' CSV HEADER;
ALTER TABLE StudentRegistrationsToDegrees add primary key (StudentRegistrationId);
COPY Teachers(TeacherId, TeacherName, Address, BirthyearTeacher, Gender) FROM '/mnt/ramdisk/tables/Teachers.table' DELIMITER ',' CSV HEADER;
ALTER TABLE Teachers add primary key (TeacherId);
COPY Courses(CourseId, CourseName, CourseDescription,  DegreeId, ECTS) FROM '/mnt/ramdisk/tables/Courses.table' DELIMITER ',' CSV HEADER;
ALTER TABLE Courses add primary key (CourseId);
COPY temp_CourseOffers(CourseOfferId, CourseId, year,  Quartile) FROM '/mnt/ramdisk/tables/CourseOffers.table' DELIMITER ',' CSV HEADER;
SELECT co.*, CourseName INTO CourseOffers FROM temp_CourseOffers co, courses c where c.courseid = co.courseid;
DROP TABLE temp_CourseOffers;
COPY TeacherAssignmentsToCourses(CourseOfferId, TeacherId) FROM '/mnt/ramdisk/tables/TeacherAssignmentsToCourses.table' DELIMITER ',' CSV HEADER;
COPY StudentAssistants(CourseOfferId, StudentRegistrationId) FROM '/mnt/ramdisk/tables/StudentAssistants.table' DELIMITER ',' CSV HEADER;
COPY temp_CourseRegistrations(CourseOfferId, StudentRegistrationId, Grade) FROM '/mnt/ramdisk/tables/CourseRegistrations.table' DELIMITER ',' CSV HEADER NULL 'null';
SELECT cr.*, srd.StudentId, CourseId INTO CourseRegistrations FROM temp_CourseRegistrations cr, CourseOffers co, StudentRegistrationsToDegrees srd WHERE cr.CourseOfferId = co.CourseOfferId and cr.StudentRegistrationId = srd.StudentRegistrationId;
DROP TABLE temp_CourseRegistrations;
ALTER TABLE CourseRegistrations add primary key (StudentRegistrationId, CourseOfferId);
ANALYZE VERBOSE;
